apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-of-the-day
  labels:
    app: frontend
spec:
  replicas: 2
  minReadySeconds: 10
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: stock-of-the-day
          image: 740966400558.dkr.ecr.eu-central-1.amazonaws.com/stock-of-the-day:3.0
          ports:
            - containerPort: 4999
          livenessProbe:
            httpGet:
              path: /api/ping
              port: 4999
            initialDelaySeconds: 15